# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  plugins:
    - custom_lint
  errors:
    avoid_print: ignore
    invalid_annotation_target: ignore # see https://github.com/rrousselGit/freezed/issues/488
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

dart_code_metrics:
  extends:
    - recommended
  rules:
    - prefer-declaring-const-constructor: false # goes against drift guide
    - no-empty-block: false # empty blocks allow me to be explicitly reminded of callbacks/options without using them
    - prefer-prefixed-global-constants: false # i don't like having to put 'k' prefix before my own constants
    - avoid-missing-enum-constant-in-map: false # it's very common (e.g. effects of tweaks on volumeAssignments) to not mention all possible enum values
    - avoid-duplicate-constant-values: false # programgroups sometimes have the same short and long name
  formatter:
    line-length: 100
