import 'package:bodybuild/data/workouts/workout_providers.dart';
import 'package:bodybuild/model/programmer/program_state.dart';
import 'package:bodybuild/model/workouts/workout.dart';
import 'package:bodybuild/model/workouts/workout_template.dart';
import 'package:bodybuild/service/template_persistence_service.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'template_provider.g.dart';

@riverpod
TemplatePersistenceService templatePersistenceService(Ref ref) {
  final database = ref.watch(workoutDatabaseProvider);
  return TemplatePersistenceService(database);
}

@riverpod
class TemplateManager extends _$TemplateManager {
  @override
  Stream<List<WorkoutTemplate>> build() {
    final service = ref.watch(templatePersistenceServiceProvider);
    return service.watchAllTemplates();
  }

  /// Persist an already-migrated [ProgramState] as workout templates.
  Future<void> importTemplatesFromProgram(ProgramState program) async {
    final templates = program.toTemplates();
    final service = ref.read(templatePersistenceServiceProvider);
    for (final template in templates) {
      await service.createTemplate(template);
    }
    ref.invalidateSelf();
  }

  /// Save a workout as a template
  Future<void> saveWorkoutAsTemplate(Workout workout, {String? name}) async {
    final programmerWorkout = workout.toProgrammerWorkout(name: name);
    final template = WorkoutTemplate(
      id: '', // Will be generated by the service
      description: workout.notes,
      isBuiltin: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      workout: programmerWorkout,
    );

    final service = ref.read(templatePersistenceServiceProvider);
    await service.createTemplate(template);
    ref.invalidateSelf();
  }

  /// Delete a template
  Future<void> deleteTemplate(String templateId) async {
    final service = ref.read(templatePersistenceServiceProvider);
    await service.deleteTemplate(templateId);
    ref.invalidateSelf();
  }
}
